# Generated by Django 2.0.5 on 2018-06-04 11:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('meetup', '0002_auto_20180531_1646'),
    ]

    operations = [
        migrations.DeleteModel(
            name='User',
        ),
    ]
