# Generated by Django 2.0 on 2018-06-07 10:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meetup', '0003_delete_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='meetup',
            name='meetup_time',
            field=models.TimeField(default='12:30 PM', verbose_name='time of meetup'),
        ),
    ]
