# Generated by Django 2.0 on 2018-06-07 10:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meetup', '0004_meetup_meetup_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='meetup',
            name='meetup_time',
            field=models.TimeField(default='12:30 PM', verbose_name='time of meetup'),
        ),
    ]
