# Generated by Django 2.0.5 on 2018-06-07 10:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meetup', '0007_auto_20180607_1548'),
    ]

    operations = [
        migrations.AlterField(
            model_name='meetup',
            name='meetup_time',
            field=models.TimeField(default='12:45 PM', verbose_name='time of meetup'),
        ),
    ]
