# Generated by Django 2.0.5 on 2018-06-07 10:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('meetup', '0008_auto_20180607_1551'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='meetup',
            name='meetup_time',
        ),
    ]
