# Generated by Django 2.0.5 on 2018-06-11 06:18

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meetup', '0009_remove_meetup_meetup_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='meetup',
            name='meetup_time',
            field=models.TimeField(default=datetime.time(10, 0), verbose_name='time of meetup'),
        ),
        migrations.AlterField(
            model_name='meetup',
            name='meetup_date',
            field=models.DateField(verbose_name='date of meetup'),
        ),
    ]
