# Generated by Django 2.0.5 on 2018-06-11 06:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('meetup', '0011_auto_20180611_1206'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='meetup',
            name='meetup_time',
        ),
    ]
