# Generated by Django 2.0.5 on 2018-06-11 11:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meetup', '0013_auto_20180611_1223'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='group',
            name='group_name',
        ),
        migrations.AddField(
            model_name='meetup',
            name='meetup_description',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.DeleteModel(
            name='Group',
        ),
    ]
