# Generated by Django 2.0.5 on 2018-06-11 11:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meetup', '0014_auto_20180611_1646'),
    ]

    operations = [
        migrations.AlterField(
            model_name='meetup',
            name='meetup_description',
            field=models.CharField(default='Nothing', max_length=500),
        ),
    ]
