# Generated by Django 2.0.5 on 2018-06-11 11:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meetup', '0015_auto_20180611_1655'),
    ]

    operations = [
        migrations.AlterField(
            model_name='meetup',
            name='meetup_description',
            field=models.CharField(max_length=500),
        ),
    ]
