# Generated by Django 2.0.5 on 2018-06-11 12:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('meetup', '0016_auto_20180611_1701'),
    ]

    operations = [
        migrations.CreateModel(
            name='Group',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('group_description', models.CharField(max_length=1000)),
                ('group_category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='meetup.Category')),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=100)),
                ('emailid', models.EmailField(max_length=200)),
            ],
        ),
        migrations.RemoveField(
            model_name='meetup',
            name='meetup_category',
        ),
        migrations.RemoveField(
            model_name='meetup',
            name='meetup_description',
        ),
        migrations.AddField(
            model_name='meetup',
            name='meetup_place',
            field=models.CharField(default='here', max_length=200),
        ),
    ]
