# Generated by Django 2.0.5 on 2018-06-12 06:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('meetup', '0017_auto_20180611_1744'),
    ]

    operations = [
        migrations.AddField(
            model_name='meetup',
            name='meetup_category',
            field=models.ForeignKey(default='1', on_delete=django.db.models.deletion.CASCADE, to='meetup.Category'),
        ),
    ]
