# Generated by Django 2.0.5 on 2018-06-12 06:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('meetup', '0018_meetup_meetup_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='meetup',
            name='meetup_category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='meetup.Category'),
        ),
    ]
