# Generated by Django 2.0.5 on 2018-06-12 06:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('meetup', '0019_auto_20180612_1131'),
    ]

    operations = [
        migrations.CreateModel(
            name='MeetupGroups',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('group_name', models.CharField(max_length=200)),
                ('meetup_date', models.DateTimeField(verbose_name='date of meetup')),
                ('meetup_place', models.CharField(default='here', max_length=200)),
                ('group_category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='meetup.Category')),
            ],
            options={
                'ordering': ['-meetup_date'],
            },
        ),
        migrations.RemoveField(
            model_name='meetup',
            name='meetup_category',
        ),
        migrations.DeleteModel(
            name='Meetup',
        ),
    ]
