# Generated by Django 2.0.5 on 2018-06-12 06:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meetup', '0021_auto_20180612_1153'),
    ]

    operations = [
        migrations.AddField(
            model_name='group',
            name='group_description',
            field=models.TextField(default=' '),
        ),
    ]
