# Generated by Django 2.0.5 on 2018-06-12 06:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meetup', '0022_group_group_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='group',
            name='group_description',
            field=models.TextField(),
        ),
    ]
