# Generated by Django 2.0.5 on 2018-06-12 07:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meetup', '0023_auto_20180612_1200'),
    ]

    operations = [
        migrations.AddField(
            model_name='group',
            name='users',
            field=models.ManyToManyField(to='meetup.User'),
        ),
    ]
