# Generated by Django 2.0.5 on 2018-06-12 12:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('meetup', '0024_group_users'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='emailid',
            new_name='email',
        ),
        migrations.RemoveField(
            model_name='group',
            name='users',
        ),
        migrations.AddField(
            model_name='meetup',
            name='created_by',
            field=models.ForeignKey(default='1', on_delete=django.db.models.deletion.CASCADE, to='meetup.User'),
        ),
    ]
