# Generated by Django 2.0.5 on 2018-06-12 13:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('meetup', '0025_auto_20180612_1753'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='meetup',
            name='created_by',
        ),
    ]
