# Generated by Django 2.0.5 on 2018-06-12 13:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('meetup', '0028_auto_20180612_1852'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='meetup',
            options={'ordering': ['-meetup_date_time']},
        ),
        migrations.RenameField(
            model_name='meetup',
            old_name='meetup_date',
            new_name='meetup_date_time',
        ),
    ]
